SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS blacklist_date;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS blacklist_date
(
  id          SMALLINT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  closed_date DATETIME                 NOT NULL
)
  ENGINE = InnoDB
  DEFAULT CHARSET = latin1;
