SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS hall_of_fame;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS hall_of_fame (
  id        SMALLINT(10) NOT NULL AUTO_INCREMENT,
  title     VARCHAR(500) NOT NULL,
  team_name VARCHAR(500) NOT NULL,
  period    VARCHAR(500) NOT NULL,
  PRIMARY KEY (id),
  KEY id (id)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = latin1;
